hellraiser/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

   root 'welcome#index'

  resources :scans

end

hellraiser/app/models/scan.rb
class Scan < ActiveRecord::Base
	validates :title, presence: true
	validates :target, presence: true
end

hellraiser/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hellraiser/app/controllers/scans_controller.rb
class ScansController < ApplicationController
	def new
		@scan ||= Scan.new
	end

	def index
		@scans = Scan.all
		
	end

	def show
		@scan = Scan.find(params[:id])
		@result = redis.get(@scan.id)
	end


	def create
		@scan = Scan.new(scan_params)
		@scan.status = 0
		if @scan.save
			Hellraiserasync.perform_async(@scan.id)
			redirect_to @scan
		else
			render 'new'
		end
	end

	def update
		@scan = Scan.find(params[:id])

		if @scan.update(scan_params)
			redirect_to @scan
		else
			render 'edit'
		end
	end

	def destroy
		@scan = Scan.find(params[:id])
		FileUtils.rm Dir.glob(HellRaiser.configuration.output_dir + @scan.id.to_s + '.*')
		redis.del @scan.id
		@scan.destroy
		redirect_to scans_path
	end

private
	def scan_params
		params.require(:scan).permit(:title, :target)
	end

	def redis
		@redis ||= Redis.new
	end

end

hellraiser/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

hellraiser/app/helpers/application_helper.rb
module ApplicationHelper
end

hellraiser/app/helpers/scans_helper.rb
module ScansHelper
end

hellraiser/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hellraiser/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HellRaiser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

hellraiser/app/views/scans/index.html.erb
<p>
<h1>Listing Scans</h1>

<table class="table">
<%= link_to 'New Scan', new_scan_path %>
<tr>
<th>Title</th>
<th>Target</th>
<th>Status</th>
<th>Show</th>
<th>Destroy</th>
</th>
<% @scans.each do |scan| %>
	<tr>
	<th><%= scan.title %></th>
	<th><%= scan.target %></th>
	<th><% if scan.status == 0 %>
  		Queued
		<% elsif scan.status == 1 %>
		Running
		<% else %>
		Finished
		<% end %>
	</th>
	<th><%= link_to 'Show', scan_path(scan) %> </th>
	<th>
	<% if scan.status == 2 %>
		<%= link_to 'Destroy', scan_path(scan),
		method: :delete,
		data: { confirm: 'Are you sure?' } %>
	<% else %>
		Destroy
	<% end %> </th>
	</tr>
<% end %>
</table>

hellraiser/app/views/scans/new.html.erb
<p>
<h1>New Scan</h1>

<%= form_for :scan, url: scans_path do |f| %>
	<% if @scan.errors.any? %>
		<div id="error_explanation">
		<h2>
		<%= pluralize(@scan.errors.count, "error") %>
		prohibited this scan from being created:
		</h2>
		<ul>
		<% @scan.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
		</div>
	<% end %>
	<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
	</p>
	<p>
	<%= f.label :target %>
	<%= f.text_field :target %>
	</p>
	<p>
	<%= f.submit "Start scan" %>
	</p>
<% end %>
<%= link_to 'Back', scans_path %>

hellraiser/app/views/scans/show.html.erb
<p>
<strong>Title:</strong>
<%= @scan.title %>
</p>
<p>
<strong>Target:</strong>
<%= @scan.target %>
</p>
<p>
<strong>Status</strong>

<% if @scan.status == 0 %>
  Queued
<% elsif @scan.status == 1 %>
  Running
<% else %>
  Finished
<% end %>
</p>

<p>
<% if @result and File.exist? @result %>
  <p>
  <% file = File.read(@result) %>
  <% scans = JSON.parse(file) %>
  <% id = 0 %>
  <% scans.each do |scan| %>
    <table>
    <tr><td>IP Address:</td><td> <%= scan['ip'] %></td></tr>
    <tr><td>Status:</td><td> <%= scan['status']['state'] %></td></tr>
    <tr><td>MAC:</td><td> <%= scan['mac'] %></td></tr>
    <tr><td>Vendor:</td><td> <%= scan['vendor'] %></td></tr>
    <tr><td>Hostnames:</td><td>
    <% scan['hostnames'].each do |h| %>
      <%= h['name'] %>
    <% end %>
    </td></tr>
    </table>
    Operation System:
    <% if scan['cpes'] %>
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <a data-toggle="collapse" href="#<%= cpe_id %>">
          <%= cpe %>
          </a>
        <% else %>
          <%= cpe %>
        <% end %>
      <% end %> 
      <% scan['cpes'].each do |(cpe,cves)| %>
        <% if cves.count > 0 %>
          <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
          <div id="<%= cpe_id %>" class="collapse">
          <%= cpe %>
          <% cves.each do |cve| %>
            <div>
            <%= link_to cve['id'], cve['idurl'] %>
            <% if cve['impact'] %>
              <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                <span style="color:red" title="Confidentiality Impact: COMPLETE">
              <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                <span style="color:orange" title="Confidentiality Impact: PARTIAL">
              <% elsif cve['impact']['confidentiality'] == "NONE" %>
                <span style="color:green" title="Confidentiality Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              C
              </span>
              <% if cve['impact']['integrity'] == "COMPLETE" %>
                <span style="color:red" title="Integrity Impact: COMPLETE">
              <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                <span style="color:orange" title="Integrity Impact: PARTIAL">
              <% elsif cve['impact']['integrity'] == "NONE" %>
                <span style="color:green" title="Integrity Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              I
              </span>
              <% if cve['impact']['availability'] == "COMPLETE" %>
                <span style="color:red" title="Availability Impact: COMPLETE">
              <% elsif cve['impact']['availability'] == "PARTIAL" %>
                <span style="color:orange" title="Availability Impact: PARTIAL">
              <% elsif cve['impact']['availability'] == "NONE" %>
                <span style="color:green" title="Availability Impact: NONE">
              <% else %>
                <span style="color:black">
              <% end %>
              A
              </span>
            <% end %>
            <% if cve['access'] %>
              <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
            <% end %>
            <% if cve['edb'] %>
              <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
            <% end %>
            <% if cve['msf'] %>
              <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
            <% end %>
            </div>
          <% end %>
        <% end %>
        </div>
      <% end %>
    <% else %>
      System not reconized
    <% end %>
    <% id = id+1 %>
    <% if scan['ports'] %>
      <table class="table table-bordered">
      <thead>
      <tr><td>Service</td><td>Banner</td><td>Port/Protocol</td><td>Status</td><td>CPEs</td></tr>
      </thead>
      <% scan['ports'].each do |port| %>
        <tr>
        <td><%= port['name'] %></td>
        <td><%= port['product'] %> <%= port['version'] %> <%= port['extra_info'] %></td>
        <td><%= port['port'] %>/<%= port['protocol'] %></td>
        <td><%= port['state'] %></td>
        <td>
        <% port['cpes'].each do |(cpe,cves)| %>
          <% if cves.count > 0 %>
            <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
            <a data-toggle="collapse" href="#<%= cpe_id %>">
            <%= cpe %>
            </a>
          <% else %>
            <%= cpe %>
          <% end %>
        <% end %>
        </td>
        </tr>
        <tr>
        <td colspan="5">
        <% port['cpes'].each do |(cpe,cves)| %>
          <% if cves.count > 0 %>
            <% cpe_id = cpe.gsub(/\.|\/|:/, '_') + id.to_s %>
            <div id="<%= cpe_id %>" class="collapse">
            <%= cpe %>
            <% cves.each do |cve| %>
              <div>
              <%= link_to cve['id'], cve['idurl'] %>
              <% if cve['impact'] %>
                <% if cve['impact']['confidentiality'] == "COMPLETE" %>
                  <span style="color:red" title="Confidentiality Impact: COMPLETE">
                <% elsif cve['impact']['confidentiality'] == "PARTIAL" %>
                  <span style="color:orange" title="Confidentiality Impact: PARTIAL">
                <% elsif cve['impact']['confidentiality'] == "NONE" %>
                  <span style="color:green" title="Confidentiality Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                C
                </span>
                <% if cve['impact']['integrity'] == "COMPLETE" %>
                  <span style="color:red" title="Integrity Impact: COMPLETE">
                <% elsif cve['impact']['integrity'] == "PARTIAL" %>
                  <span style="color:orange" title="Integrity Impact: PARTIAL">
                <% elsif cve['impact']['integrity'] == "NONE" %>
                  <span style="color:green" title="Integrity Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                I
                </span>
                <% if cve['impact']['availability'] == "COMPLETE" %>
                  <span style="color:red" title="Availability Impact: COMPLETE">
                <% elsif cve['impact']['availability'] == "PARTIAL" %>
                  <span style="color:orange" title="Availability Impact: PARTIAL">
                <% elsif cve['impact']['availability'] == "NONE" %>
                  <span style="color:green" title="Availability Impact: NONE">
                <% else %>
                  <span style="color:black">
                <% end %>
                A
                </span>
              <% end %>
              <% if cve['access'] %>
                <%= image_tag(cve['access']['vector'] + ".png", width: "20", height: "20", title: "ACCESS: " + cve['access']['vector']) %>
              <% end %>
              <% if cve['edb'] %>
                <%= link_to image_tag("edb.png", width: "20", height:"20", title: "Exploit-DB"), cve['edb'] %>
              <% end %>
              <% if cve['msf'] %>
               <%= link_to image_tag("msf.png", width: "20", height:"20", title: "Metasploit"), cve['msf'] %>
              <% end %>
              </div>
            <% end %>
          <% end %>
          </div>
        <% end %>
        </td>
        </tr>
        <% id = id+1 %>
      <% end %>
      </table>
    <% end %>
  <% end %>
<% end %>
<p>
<%= link_to 'Back', scans_path %>
</p>

hellraiser/app/views/welcome/index.html.erb
<p>
<h1>HellRaiser</h1>
<p> <%= link_to 'HellRaiser', controller: 'scans'%></p>